### ISSUE TITLE
No IPv4 address returned, instead error code 301

### ISSUE THREAD

**Issue by solarjoe** [gtwy/IPv6forDuckDNS#1]
Using 

`ipv4service="https://gtwy.net/ip"`

with curl returns 

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
```

To fix it you have to append a trailing slash to the URL:

`ipv4service="https://gtwy.net/ip/"`

Browsers do this automatically, curl does not seem to do it.

**Comment by gtwy** [comment]
Interesting.

I can fix this, but the problem is that gtwy.net is now on an IPv6 service, so it will most likely return your IPv6 address.

For now, you'll have to use another IPv4 lookup tool when running the autoconfig. I'll work on fixing this in the next couple days and push out a patch. Thanks for letting me know.

**Comment by solarjoe** [comment]
It works fine in your script, the `curl --ipv4` returns the IPv4. But my browser also displays IPv6.

**Comment by gtwy** [comment]
I added the trailing / to the default URL. Thanks for catching this.

https://github.com/gtwy/IPv6forDuckDNS/commit/015c636d4e739455eb38353d787ce15672cb50d8#diff-6fd8e15aae27781592c029aca4899bdd
